### ISSUE TITLE
Calibration video

### ISSUE THREAD

**Issue by GerardHarkemaAvans** [mangdangroboticsclub/MiniPupperDocs#11]
Where is the "The video is shown as below. ビデオは以下のように表示されます" in the calibration section?

**Comment by skellig-ai** [comment]
Hi,Followed the instructions, when I start the calibration tool nothing happens, the legs don't move. 
If you have any suggestions I'd really apprecieate it.

**Comment by mangdangroboticsclub** [comment]
Quick Calibration Guide
Please confirm the below link for quick and easy calibration, thanks!
https://minipupperdocs.readthedocs.io/en/latest/guide/Software.html#calibration
