### ISSUE TITLE
Cannot connect hip servo to hipmodule

### ISSUE THREAD

**Issue by Skammi** [mangdangroboticsclub/MiniPupperDocs#28]
There is a copper pice in the hip module where the hip serve should be entered.
![Hip-modules_and_hip-servos](https://user-images.githubusercontent.com/12001204/192049475-393ff9fc-d0fc-423a-9e92-549af83eda6a.jpg)

**Comment by mangdangroboticsclub** [comment]
It's a super early version :)
Please refer to the below video link, 
https://www.youtube.com/watch?v=9rqtKn5ccyc
If you have any support, please send an email to sales@mangdang.net
Best,
Thanks!
