### ISSUE TITLE
Mini Pupper v2 Mechanical Model

### ISSUE THREAD

**Issue by gmacario** [mangdangroboticsclub/MiniPupperDocs#29]
Hello and many thanks for the comprehensive documentation!

I have been working on an Open Source project which is centered around the [Mini Pupper 2](https://www.kickstarter.com/projects/336477435/mini-pupper-2-open-source-ros2-robot-kit-for-dreamers).

For this project we would like to design an adjustable adapter for the [OAK-D Lite](https://shop.luxonis.com/products/oak-d-lite-1) smart camera.

Since the project has strict timelines I have a few questions:

1. Does the "[Fusion 360 CAD model](https://a360.co/3wFLSlT)" referenced on page https://github.com/mangdangroboticsclub/MiniPupperDocs/blob/main/docs/reference/Design.rst refer to v1 of [Mini Pupper](https://www.kickstarter.com/projects/336477435/mini-pupper-open-sourceros-robot-dog-kit) or v2?
2. If it is not v2, is the v2 model available somewhere else?
3. If the v2 model is not yet public, what is the expected timeline to make it public?

Thank you very much in advance!

**Comment by mangdangroboticsclub** [comment]
Thanks for your questions.
1. it's refer to v1.
2. We have not Fusion 360 CAD model for mini pupper 2, the only different point is the top part. 
3. we have not clear timeline to public it.

you can connect the camera module to the USB connector directly, why do you need to design the adjustable adapter for the camera? could you please let us'pen source project? if yes, could you please let us know the link?
We'll study your project and then confirm how to support you.
Thanks!

**Comment by gmacario** [comment]
Hello @mangdangroboticsclub, nice to meet you!

Many thanks for your quick reply, Let me try answer your questions.

> will you open source your project? if yes, could you please let us know the link?

First of all let me introduce myself. My name is Gianpaolo Macario and I am a founding member of the [B-AROL-O Team](https://github.com/B-AROL-O).

Last year together with a couple of friends and colleagues ([Alessandro](https://github.com/alv67) and [Gianluca](https://github.com/gteti)) I participated to the [OpenCV Spatial AI Contest](https://opencv.org/opencv-spatial-ai-contest/) with project [ARNEIS](https://arneis.readthedocs.io/) (short for `A`utomated `R`ecognizer, `N`etwork-`E`nabled, `I`tem `S`orter).

We had a lot of fun when working on the project, and much to our surprise we eventually were [Winner of the OpenCV Spatial AI Contest Popular Vote](https://opencv.org/blog/2022/06/13/announcing-the-opencv-spatial-ai-contest-popular-vote-winner/).

Since then, the B-AROL-O Team has grown, project ARNEIS is still progressing - [it is an Open Source project, by the way...](https://github.com/B-AROL-O/ARNEIS)

As soon as the new [OpenCV AI Competition 2023]() was announced, we decided to join again with a new project is called FREISA (again, an acronym which I will invite you to guess - or just check on <https://www.hackster.io/projects/845012>)

On FREISA I have only the role of Advisor. FREISA is developed by a new team of 4 members (Andrea, Davide, Eric and Pietro).
I have a feeling that you know at least one of them...

> you can connect the camera module to the USB connector directly, why do you need to design the adjustable adapter for the camera?

I will leave the FREISA team members to answer.

> We'll study your project and then confirm how to support you.

Thanks a lot in advance on behalf of the B-AROL-O Team!

**Comment by mangdangroboticsclub** [comment]
Dear Gianpaolo Macario,

Thanks a lot for your introduction.
Yes, Eric helped us so much before.
Let's discuss this topic by email, my email address is afreez@mangdang.net

Best,
Afreez

**Comment by gmacario** [comment]
@mangdangroboticsclub released the 3D Model of the Mini Pupper 2 in .3MF format.

Mini Pupper 2 Fusion 360 CAD model is available at: https://a360.co/485n8mP

Thanks @mangdangroboticsclub. Closing issue
