### ISSUE TITLE
Potential Security Issues of Camera Module for Mini Pupper 2?

### ISSUE THREAD

**Issue by gmacario** [mangdangroboticsclub/MiniPupperDocs#31]
Hello @mangdangroboticsclub and sorry if this is not the most appropriate place to ask this question.
Feel free to direct me to the correct forum/mailing list/etc.

I just read the following statement on https://mangdang.store/products/mini-pupper-2-ai-robot-smart-robot-quadruped-robot-educational-robot-genuine-open-source-stem-k12:

> **Camera module**: For potential security issues, the camera module is not included in our default package. If you want to explore camera AI functions, you can choose a normal USB camera module, of course, a 3D camera module is better for study.

What do you exactly mean with "security issues" there?

As you know our plan for [Project FREISA](https://www.hackster.io/projects/845012) is to use Mini Pupper 2 together with the [OAK-D LITE](https://docs.luxonis.com/projects/hardware/en/latest/pages/DM9095/) stereo camera, therefore any hints or advices is warmly welcome.

Thanks in advance!

**Comment by mangdangroboticsclub** [comment]
Sorry, I just saw your comments here.
There will be no impact on your project. What I mean is that some people are more sensitive to camera products and worry about collecting private data.

**Comment by hubertsmits** [comment]
Apologies for using this thread. Where do I post a MiniPupper 1 for sale?
